fix: switch to the official source to fix the Dependabot error
Dependabot encountered '1' error(s) during execution, please check the logs for more details.
+------------------------------------------------------------------------------------+
|                           Dependencies failed to update                            |
+-----------------------+-----------------------------+------------------------------+
| Dependency            | Error Type                  | Error Details                |
+-----------------------+-----------------------------+------------------------------+
| docker/library/alpine | private_source_bad_response | {                            |
|                       |                             |   "source": "public.ecr.aws" |
|                       |                             | }                            |
+-----------------------+-----------------------------+------------------------------+
Failure running container 5d66983a0df18a3a7649271375752ec92785f22d22d0a861db547b674a9ef725: Error: Command failed with exit code 1: /bin/sh -c $DEPENDABOT_HOME/dependabot-updater/bin/run update_files
Cleaned up container 5d66983a0df18a3a7649271375752ec92785f22d22d0a861db547b674a9ef725
  proxy | 2026/01/15 09:01:22 45/149 calls cached (30%)
2026/01/15 09:01:22 Posting metrics to remote API endpoint
Error: Dependabot encountered an error performing the update

Signed-off-by: honeok <i@honeok.com>